fieldLayouts:
  6d1a0104-1bb9-4c8e-9c92-9b44eb8102d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b872d4d1-a4a8-43e1-aa40-12f3f9cccc65 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53fc4f8b-7e2d-4f44-9f3c-f88153e13298
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a6d4a7e6-98a4-4625-a5f5-30a635d92bba
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
