fieldLayouts:
  51fca31e-16c5-40a5-a1f8-bacec3173c23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 00d54e49-dda0-48f1-a3b5-7c20a87dedda # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1739e2d4-25ff-4411-8027-ccf352c59ebd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1201eb0e-201b-404c-b9f5-ca925962427e
        userCondition: null
handle: header
name: Header
sortOrder: 1
