defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  d9a8c388-aac9-49e4-a1f4-504f99eed1a7: # motoventure
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
