defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  50831325-14d5-4a9d-ad1a-0f7fb68a3124: # SwimThinks
    enabledByDefault: true
    hasUrls: true
    template: blog/index.twig
    uriFormat: __home__
type: single
